### ISSUE TITLE
Pre-trained generative model (key model) checkpoints

### ISSUE THREAD

**Issue by Werty18** [suzhigangssz/AVIH#1]
Hi, thanks for the great work. Can you please provide the weights of your pre-trained generative model (key model)? Thanks.

**Comment by suzhigangssz** [comment]
Thank you for your interest, we have added the link to the Preparation section in README.md.

**Comment by suzhigangssz** [comment]
> Hi, thanks for the great work. Can you please provide the weights of your pre-trained generative model (key model)? Thanks.

Thank you for your interest, we have added the link to the Preparation section in README.md.
