### ISSUE TITLE
doubts in the article

### ISSUE THREAD

**Issue by dreamtojava** [suzhigangssz/AVIH#5]
Hello，author，May I ask how the service model is obtained? Can the service model classify both the original and the protected image?Thank you, thank you very much.

**Comment by suzhigangssz** [comment]
> Hello，author，May I ask how the service model is obtained? Can the service model classify both the original and the protected image?Thank you, thank you very much.

1. The service model is a pre-trained model, we provide the address to download it in the open source code.
2. The service model can classify both original and protected images. We did not change the service model in the process of generating protected images.
